### PR TITLE
feat(SYN-672): Update accessibility controls

### PR DESCRIPTION
**Pull request by jrparish**

### CODE REVIEW

**Comment by go2guy** [comment]
Approved!   HAHA!  Might need be taken off the list :)

**Comment by zyoutz-r7** [comment]
I sure thought I removed myself too, but clearly not.  Hi you guys!

**Comment by jrparish** [comment]
@go2guy @zyoutz-r7  Hi guys! You might need to "Unwatch" this repository to stop receiving notifications.

**Review by bparish628 — APPROVED** [review]
Looks good!

**Pull request merged**
